// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

import (
	"homework/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OrderPackagerStrategyMock implements mm_packager.OrderPackagerStrategy
type OrderPackagerStrategyMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPackageOrder          func(order domain.PVZOrder) (p1 domain.PVZOrder, err error)
	funcPackageOrderOrigin    string
	inspectFuncPackageOrder   func(order domain.PVZOrder)
	afterPackageOrderCounter  uint64
	beforePackageOrderCounter uint64
	PackageOrderMock          mOrderPackagerStrategyMockPackageOrder
}

// NewOrderPackagerStrategyMock returns a mock for mm_packager.OrderPackagerStrategy
func NewOrderPackagerStrategyMock(t minimock.Tester) *OrderPackagerStrategyMock {
	m := &OrderPackagerStrategyMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PackageOrderMock = mOrderPackagerStrategyMockPackageOrder{mock: m}
	m.PackageOrderMock.callArgs = []*OrderPackagerStrategyMockPackageOrderParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderPackagerStrategyMockPackageOrder struct {
	optional           bool
	mock               *OrderPackagerStrategyMock
	defaultExpectation *OrderPackagerStrategyMockPackageOrderExpectation
	expectations       []*OrderPackagerStrategyMockPackageOrderExpectation

	callArgs []*OrderPackagerStrategyMockPackageOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderPackagerStrategyMockPackageOrderExpectation specifies expectation struct of the OrderPackagerStrategy.PackageOrder
type OrderPackagerStrategyMockPackageOrderExpectation struct {
	mock               *OrderPackagerStrategyMock
	params             *OrderPackagerStrategyMockPackageOrderParams
	paramPtrs          *OrderPackagerStrategyMockPackageOrderParamPtrs
	expectationOrigins OrderPackagerStrategyMockPackageOrderExpectationOrigins
	results            *OrderPackagerStrategyMockPackageOrderResults
	returnOrigin       string
	Counter            uint64
}

// OrderPackagerStrategyMockPackageOrderParams contains parameters of the OrderPackagerStrategy.PackageOrder
type OrderPackagerStrategyMockPackageOrderParams struct {
	order domain.PVZOrder
}

// OrderPackagerStrategyMockPackageOrderParamPtrs contains pointers to parameters of the OrderPackagerStrategy.PackageOrder
type OrderPackagerStrategyMockPackageOrderParamPtrs struct {
	order *domain.PVZOrder
}

// OrderPackagerStrategyMockPackageOrderResults contains results of the OrderPackagerStrategy.PackageOrder
type OrderPackagerStrategyMockPackageOrderResults struct {
	p1  domain.PVZOrder
	err error
}

// OrderPackagerStrategyMockPackageOrderOrigins contains origins of expectations of the OrderPackagerStrategy.PackageOrder
type OrderPackagerStrategyMockPackageOrderExpectationOrigins struct {
	origin      string
	originOrder string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Optional() *mOrderPackagerStrategyMockPackageOrder {
	mmPackageOrder.optional = true
	return mmPackageOrder
}

// Expect sets up expected params for OrderPackagerStrategy.PackageOrder
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Expect(order domain.PVZOrder) *mOrderPackagerStrategyMockPackageOrder {
	if mmPackageOrder.mock.funcPackageOrder != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by Set")
	}

	if mmPackageOrder.defaultExpectation == nil {
		mmPackageOrder.defaultExpectation = &OrderPackagerStrategyMockPackageOrderExpectation{}
	}

	if mmPackageOrder.defaultExpectation.paramPtrs != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by ExpectParams functions")
	}

	mmPackageOrder.defaultExpectation.params = &OrderPackagerStrategyMockPackageOrderParams{order}
	mmPackageOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPackageOrder.expectations {
		if minimock.Equal(e.params, mmPackageOrder.defaultExpectation.params) {
			mmPackageOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPackageOrder.defaultExpectation.params)
		}
	}

	return mmPackageOrder
}

// ExpectOrderParam1 sets up expected param order for OrderPackagerStrategy.PackageOrder
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) ExpectOrderParam1(order domain.PVZOrder) *mOrderPackagerStrategyMockPackageOrder {
	if mmPackageOrder.mock.funcPackageOrder != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by Set")
	}

	if mmPackageOrder.defaultExpectation == nil {
		mmPackageOrder.defaultExpectation = &OrderPackagerStrategyMockPackageOrderExpectation{}
	}

	if mmPackageOrder.defaultExpectation.params != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by Expect")
	}

	if mmPackageOrder.defaultExpectation.paramPtrs == nil {
		mmPackageOrder.defaultExpectation.paramPtrs = &OrderPackagerStrategyMockPackageOrderParamPtrs{}
	}
	mmPackageOrder.defaultExpectation.paramPtrs.order = &order
	mmPackageOrder.defaultExpectation.expectationOrigins.originOrder = minimock.CallerInfo(1)

	return mmPackageOrder
}

// Inspect accepts an inspector function that has same arguments as the OrderPackagerStrategy.PackageOrder
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Inspect(f func(order domain.PVZOrder)) *mOrderPackagerStrategyMockPackageOrder {
	if mmPackageOrder.mock.inspectFuncPackageOrder != nil {
		mmPackageOrder.mock.t.Fatalf("Inspect function is already set for OrderPackagerStrategyMock.PackageOrder")
	}

	mmPackageOrder.mock.inspectFuncPackageOrder = f

	return mmPackageOrder
}

// Return sets up results that will be returned by OrderPackagerStrategy.PackageOrder
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Return(p1 domain.PVZOrder, err error) *OrderPackagerStrategyMock {
	if mmPackageOrder.mock.funcPackageOrder != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by Set")
	}

	if mmPackageOrder.defaultExpectation == nil {
		mmPackageOrder.defaultExpectation = &OrderPackagerStrategyMockPackageOrderExpectation{mock: mmPackageOrder.mock}
	}
	mmPackageOrder.defaultExpectation.results = &OrderPackagerStrategyMockPackageOrderResults{p1, err}
	mmPackageOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPackageOrder.mock
}

// Set uses given function f to mock the OrderPackagerStrategy.PackageOrder method
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Set(f func(order domain.PVZOrder) (p1 domain.PVZOrder, err error)) *OrderPackagerStrategyMock {
	if mmPackageOrder.defaultExpectation != nil {
		mmPackageOrder.mock.t.Fatalf("Default expectation is already set for the OrderPackagerStrategy.PackageOrder method")
	}

	if len(mmPackageOrder.expectations) > 0 {
		mmPackageOrder.mock.t.Fatalf("Some expectations are already set for the OrderPackagerStrategy.PackageOrder method")
	}

	mmPackageOrder.mock.funcPackageOrder = f
	mmPackageOrder.mock.funcPackageOrderOrigin = minimock.CallerInfo(1)
	return mmPackageOrder.mock
}

// When sets expectation for the OrderPackagerStrategy.PackageOrder which will trigger the result defined by the following
// Then helper
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) When(order domain.PVZOrder) *OrderPackagerStrategyMockPackageOrderExpectation {
	if mmPackageOrder.mock.funcPackageOrder != nil {
		mmPackageOrder.mock.t.Fatalf("OrderPackagerStrategyMock.PackageOrder mock is already set by Set")
	}

	expectation := &OrderPackagerStrategyMockPackageOrderExpectation{
		mock:               mmPackageOrder.mock,
		params:             &OrderPackagerStrategyMockPackageOrderParams{order},
		expectationOrigins: OrderPackagerStrategyMockPackageOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPackageOrder.expectations = append(mmPackageOrder.expectations, expectation)
	return expectation
}

// Then sets up OrderPackagerStrategy.PackageOrder return parameters for the expectation previously defined by the When method
func (e *OrderPackagerStrategyMockPackageOrderExpectation) Then(p1 domain.PVZOrder, err error) *OrderPackagerStrategyMock {
	e.results = &OrderPackagerStrategyMockPackageOrderResults{p1, err}
	return e.mock
}

// Times sets number of times OrderPackagerStrategy.PackageOrder should be invoked
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Times(n uint64) *mOrderPackagerStrategyMockPackageOrder {
	if n == 0 {
		mmPackageOrder.mock.t.Fatalf("Times of OrderPackagerStrategyMock.PackageOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPackageOrder.expectedInvocations, n)
	mmPackageOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPackageOrder
}

func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) invocationsDone() bool {
	if len(mmPackageOrder.expectations) == 0 && mmPackageOrder.defaultExpectation == nil && mmPackageOrder.mock.funcPackageOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPackageOrder.mock.afterPackageOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPackageOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PackageOrder implements mm_packager.OrderPackagerStrategy
func (mmPackageOrder *OrderPackagerStrategyMock) PackageOrder(order domain.PVZOrder) (p1 domain.PVZOrder, err error) {
	mm_atomic.AddUint64(&mmPackageOrder.beforePackageOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmPackageOrder.afterPackageOrderCounter, 1)

	mmPackageOrder.t.Helper()

	if mmPackageOrder.inspectFuncPackageOrder != nil {
		mmPackageOrder.inspectFuncPackageOrder(order)
	}

	mm_params := OrderPackagerStrategyMockPackageOrderParams{order}

	// Record call args
	mmPackageOrder.PackageOrderMock.mutex.Lock()
	mmPackageOrder.PackageOrderMock.callArgs = append(mmPackageOrder.PackageOrderMock.callArgs, &mm_params)
	mmPackageOrder.PackageOrderMock.mutex.Unlock()

	for _, e := range mmPackageOrder.PackageOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmPackageOrder.PackageOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPackageOrder.PackageOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmPackageOrder.PackageOrderMock.defaultExpectation.params
		mm_want_ptrs := mmPackageOrder.PackageOrderMock.defaultExpectation.paramPtrs

		mm_got := OrderPackagerStrategyMockPackageOrderParams{order}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.order != nil && !minimock.Equal(*mm_want_ptrs.order, mm_got.order) {
				mmPackageOrder.t.Errorf("OrderPackagerStrategyMock.PackageOrder got unexpected parameter order, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPackageOrder.PackageOrderMock.defaultExpectation.expectationOrigins.originOrder, *mm_want_ptrs.order, mm_got.order, minimock.Diff(*mm_want_ptrs.order, mm_got.order))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPackageOrder.t.Errorf("OrderPackagerStrategyMock.PackageOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPackageOrder.PackageOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPackageOrder.PackageOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmPackageOrder.t.Fatal("No results are set for the OrderPackagerStrategyMock.PackageOrder")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmPackageOrder.funcPackageOrder != nil {
		return mmPackageOrder.funcPackageOrder(order)
	}
	mmPackageOrder.t.Fatalf("Unexpected call to OrderPackagerStrategyMock.PackageOrder. %v", order)
	return
}

// PackageOrderAfterCounter returns a count of finished OrderPackagerStrategyMock.PackageOrder invocations
func (mmPackageOrder *OrderPackagerStrategyMock) PackageOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPackageOrder.afterPackageOrderCounter)
}

// PackageOrderBeforeCounter returns a count of OrderPackagerStrategyMock.PackageOrder invocations
func (mmPackageOrder *OrderPackagerStrategyMock) PackageOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPackageOrder.beforePackageOrderCounter)
}

// Calls returns a list of arguments used in each call to OrderPackagerStrategyMock.PackageOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPackageOrder *mOrderPackagerStrategyMockPackageOrder) Calls() []*OrderPackagerStrategyMockPackageOrderParams {
	mmPackageOrder.mutex.RLock()

	argCopy := make([]*OrderPackagerStrategyMockPackageOrderParams, len(mmPackageOrder.callArgs))
	copy(argCopy, mmPackageOrder.callArgs)

	mmPackageOrder.mutex.RUnlock()

	return argCopy
}

// MinimockPackageOrderDone returns true if the count of the PackageOrder invocations corresponds
// the number of defined expectations
func (m *OrderPackagerStrategyMock) MinimockPackageOrderDone() bool {
	if m.PackageOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PackageOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PackageOrderMock.invocationsDone()
}

// MinimockPackageOrderInspect logs each unmet expectation
func (m *OrderPackagerStrategyMock) MinimockPackageOrderInspect() {
	for _, e := range m.PackageOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderPackagerStrategyMock.PackageOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPackageOrderCounter := mm_atomic.LoadUint64(&m.afterPackageOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PackageOrderMock.defaultExpectation != nil && afterPackageOrderCounter < 1 {
		if m.PackageOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderPackagerStrategyMock.PackageOrder at\n%s", m.PackageOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderPackagerStrategyMock.PackageOrder at\n%s with params: %#v", m.PackageOrderMock.defaultExpectation.expectationOrigins.origin, *m.PackageOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPackageOrder != nil && afterPackageOrderCounter < 1 {
		m.t.Errorf("Expected call to OrderPackagerStrategyMock.PackageOrder at\n%s", m.funcPackageOrderOrigin)
	}

	if !m.PackageOrderMock.invocationsDone() && afterPackageOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderPackagerStrategyMock.PackageOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PackageOrderMock.expectedInvocations), m.PackageOrderMock.expectedInvocationsOrigin, afterPackageOrderCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderPackagerStrategyMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPackageOrderInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderPackagerStrategyMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderPackagerStrategyMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPackageOrderDone()
}
